from orderedlist import OrderedList, Node


if __name__ == '__main__':
    orderedlist1 = OrderedList(True)
    orderedlist1.add(2)
    orderedlist1.add(3)
    orderedlist1.add(4)
    orderedlist1.print_all_nodes()
    print('---------------------')
    orderedlist2 = OrderedList(False)
    orderedlist2.add(2)
    orderedlist2.add(3)
    orderedlist2.add(4)
    orderedlist2.print_all_nodes()
    print('---------------------')
    orderedlist2.clean(True)
    orderedlist2.add(2)
    orderedlist2.add(3)
    orderedlist2.add(4)
    orderedlist2.add(5)
    orderedlist2.add(6)
    orderedlist2.add(7)
    orderedlist2.delete(7)
    orderedlist2.add(12)
    orderedlist2.add(13)
    orderedlist2.add(14)
    orderedlist2.print_all_nodes()
    print('---------------------')
    orderedlist2.clean(False)
    orderedlist2.add(2)
    orderedlist2.add(3)
    orderedlist2.add(4)
    orderedlist2.add(5)
    orderedlist2.add(6)
    orderedlist2.add(7)
    orderedlist2.delete(8)
    orderedlist2.add(12)
    orderedlist2.add(13)
    orderedlist2.add(14)
    orderedlist2.print_all_nodes()
    print('---------------------')